//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imaOcjenu
    {
        public int id { get; set; }
        public int idUcenik { get; set; }
        public int idPredmet { get; set; }
        public int idKategorija { get; set; }
        public System.DateTime datum { get; set; }
        public int ocjena { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual Predmet Predmet { get; set; }
    }
}
