//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eDnevnik : DbContext
    {
        public eDnevnik()
            : base("name=eDnevnik")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<imaBiljesku> imaBiljesku { get; set; }
        public virtual DbSet<imaIzostanak> imaIzostanak { get; set; }
        public virtual DbSet<imaOcjenu> imaOcjenu { get; set; }
        public virtual DbSet<Kategorija> Kategorija { get; set; }
        public virtual DbSet<Mjesto> Mjesto { get; set; }
        public virtual DbSet<Osoba> Osoba { get; set; }
        public virtual DbSet<Predaje> Predaje { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Razred> Razred { get; set; }
        public virtual DbSet<Skola> Skola { get; set; }
    }
}
