//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public string idOsoba { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datumRodjenja { get; set; }
        public string adresa { get; set; }
        public string idMjesto { get; set; }
        public string OIB { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual Mjesto Mjesto { get; set; }
    }
}
