//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predaje
    {
        public int idProfesor { get; set; }
        public int idRazred { get; set; }
        public int idPredmet { get; set; }
    
        public virtual Osoba Osoba { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual Razred Razred { get; set; }
    }
}
