//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class imaBiljesku
    {
        public int id { get; set; }
        public int idUcenik { get; set; }
        public int idPredmet { get; set; }
        public System.DateTime datum { get; set; }
        public string biljeska { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        public virtual Ucenik Ucenik { get; set; }
    }
}
